# https://taskfile.dev

version: "3"

vars: {}

tasks:
  list:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - task --list-all
    silent: true

  remove_system_files:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - find . -name ".DS_Store" -delete -print
    silent: true

  test:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - |
        echo "test mermaid"
        mmdc -i samples/mermaid/001.mmd --puppeteerConfigFile /home/vscode/puppeteer-config.json
      - |
        echo "test plantuml"
        plantuml samples/plantuml/001.puml
    silent: true
